# Generated by Django 5.2 on 2025-08-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_position_data_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='data_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
