# Generated by Django 5.2 on 2025-08-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_alter_position_data_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='data_time',
            new_name='date_time',
        ),
    ]
