# Generated by Django 5.2 on 2025-08-15 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_rename_data_time_position_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
