# Generated by Django 5.2 on 2025-08-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_alter_position_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
    ]
