# Generated by Django 5.2 on 2025-08-20 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_subscribe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
